# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #
#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini
darkmode: true

# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

creative_commons:
  license: by-nc-sa
  size: big
  sidebar: true

# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2022
  icon:
    name: fa fa-heart
    animated: true
    color: "#808080"
  copyright: Leo