# ============================================================= #
# ====================== Scheme Settings ====================== #
#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini
darkmode: true

# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

creative_commons:
  license: by-nc-sa
  size: big
  sidebar: true

# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
toc:
  enable: true
  number: true
  wrap: true

# ============================================================= #
# ====================== Footer Settings ====================== #
footer:
  since: 2022
  icon:
    name: fa fa-heart
    animated: true
    color: "#808080"
  copyright: Leo

# ======================= Menu Settings ======================= #
# menu最大；
# 下设第一级放在sidebar，
# 第二级为顶栏，第三级为顶栏第二行
menu:
  # home: / || fa fa-bell
  Docs:
    default: /notes/ || fa fa-book
    深度学习:
      default: /deepl/ || fa fa-magic